### ISSUE TITLE
Option to sort by submit date instead of lexicographically

### ISSUE THREAD

**Issue by JoshKarpel** [JoshKarpel/condor_watch_q#24]
Right now we always sort by the value of the grouping column. `condor_q` instead sorts by submit date. If we do a query we may actually know the cluster submit date; if we don't, a good proxy might be the first event timestamp we see for that cluster.

I think it's debatable whether the default sort should be lexicographic or submit date, but for historical reasons submit date might be the way to go (that's how `condor_q` does it...).

**Comment by bbockelm** [comment]
Note that by construction you can also sort on cluster ID if QDate is not known.

**Comment by JoshKarpel** [comment]
Good point! Depends on whether we also want to actually show the submission date, which might be useful for people who don't set batch ids.

**Comment by JoshKarpel** [comment]
Jotting down some thoughts...

Your standard user doesn't set batch names. For them, submissions are largely identified by **order** and **submission time** ("the second batch of jobs I submitted", "the jobs I submitted yesterday morning"). For them, we want to order by submit date/clusterid, because the batch name is not significantly more meaningful... unless they happen to be using DAGMan, in which case grouping by batch name regains its meaning because the jobs in the DAG share a batch name but not a cluster id.

If you **do** set batch names yourself, you probably want to order them lexicographically, because (if your naming scheme is meaningful), you probably wants batches with similar names to appear near each other (even if it's just `run-1`, `run-2`, ...). You'll still want the option to sort by submission date though.

I'm _this_ close to thinking we should set the default grouping and sorting options by some system of rules based on what we discover in the initial query. Maybe just "if any batch names are **not** the Condor-set default, the default grouping is by batch name and the sorting is lexicographic. If not, the default grouping is by clusterid and we sort by submission date and then clusterid if submission date is not available".

**Comment by bbockelm** [comment]
Hi @JoshKarpel -

I'm distrustful of "magic behavior".  We really ought to have a deterministic default for sorting (adhering to the `condor_q` behavior unless we can clearly articulate why it's wrong as in the case with `-cluster`) and be able to give an option for overriding this.

Let's go with sorting by earliest jobid in the batch (as that's our understanding of `condor_q`'s behavior).

Brian
