### ISSUE TITLE
Format table according to terminal width

### ISSUE THREAD

**Issue by elin1231** [JoshKarpel/condor_watch_q#33]
Print formatting breaks when terminal is not large enough to fit all the data.

**Comment by JoshKarpel** [comment]
For the moment, you should write this like I did with the redone `make_progress_bar`, where it takes the maximum width as one of its arguments. We'll determine the maximum width in `watch_q` (somehow; there's some rough code for it already).

**Comment by JoshKarpel** [comment]
Resolved
