### ISSUE TITLE
Implement progress bar for each row

### ISSUE THREAD

**Issue by elin1231** [JoshKarpel/condor_watch_q#41]

**Comment by JoshKarpel** [comment]
I think the important thing to keep in mind here is: how do users choose what information to display? So far I've been doing lots of binary toggles of which parts of the display to show. Is this another one? It seems like this should be opt-in and the table should be the default... but maybe it should be the opposite? Things to think about.

**Comment by JoshKarpel** [comment]
Resolved by #47
