### ISSUE TITLE
Can't detect console width on Windows machines

### ISSUE THREAD

**Issue by elin1231** [JoshKarpel/condor_watch_q#44]

**Comment by elin1231** [comment]
Current way of determining console width relies on get_linux_console_width() method. The implementation works on linux based OS. The truncating to fit to console width relies on the fact that we know the console width. We need to find another way to determine console width on windows.

**Comment by JoshKarpel** [comment]
Resolved in https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=7343
